name: Lint + Test (Python)

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint Python with Black
        run: black . --check --verbose

      - name: Lint SQL with SQLFluff
        run: sqlfluff lint src/flask_imessage/sql

      - name: Run unit tests with Pytest
        run: pytest --verbose --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          name: ${{matrix.python-version}}
          file: ./coverage.xml
        continue-on-error: true # I don't care THAT much about codecov